language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

licenses:
   - 'android-sdk-license-.+'

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

before_script:
  - adb shell input keyevent 82 &
  - android-wait-for-emulator
  - adb wait-for-device

script:
  - ./gradlew connectedAndroidTest