language: android
jdk: oraclejdk8

addons:
  sonarqube: true

sonarqube:
  branches:
  - master
  - FixIssuesJapa

env:
  global:
    - secure: f3WJOr9GEw2PGihRoQ0ugazgPZvhmAxhYOD8zjDHFE2NTPqxdTzUekmRMZA1Ys/tbkcEhoa1mgpO8wxdyhB/X7SdFXV9Ch2tJ127k8LwWD//iAPFjZGkb7CQx+z5tg+pKhq/IiTW7PA34+rlyE7SFCuLPmJZHy72NAobL7KatxZzWiiGPzVqTtYMjHkBebV2jMpmxNGSNh7IbsU43q9uWmHTgLzBZ+35cV9OV0bwDHMdgeEK+Kp8+WYSr43VGRVbk0lfjgIAk+VAcIO36LXTZFDs5jbaL1RGDXIgKEfHFVtPu52TJWf8CcmRbi9BpZWMBXvOzgMX7yMvVbeuE/KkB9s0Lftr9QXS6yv9vhQJzn57U3+u7akFEWp9+yDT4ZJ4gkhqfvQUizzfZXD+uSsvJodPielIQDsgPsW1at3KfaJkoasSB/OX5h9HT3STGCM2JTPzAC56oeVHR/YtWPs+uwdlxylPpH2BS021gMl+xWV79agpXQ7rkfX1xIu0WXmgkUelYg+AjO8WHU3JrE9HL35sS6iGEdAB3mu0g4YZg1vlFMAGcynve3Uy5E/1ZbAcTY2r523jfRsafZdUaIwMWlxFMcevQjxtOxTJ8SnFgm1n6B8V9b3jXgEvukUU1BKC5iHJUGAUYLtFSWNfmwb8akBeBI3SY+4FoRImzBhU5lQ=
    - ADB_INSTALL_TIMEOUT=10
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-24
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb shell input keyevent 82 &
  - android-wait-for-emulator

script:
  - adb devices
  - sonar-scanner -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN

notifications:
  email: false
