language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

licenses:
   - 'android-sdk-license-.+'

before_script:
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest